logging:
  level:
    root: INFO
  file:
    name: /logs/spring-boot/student-service.log

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

#  console available at : http://localhost:8080/h2-console
#  references: https://www.baeldung.com/spring-boot-h2-database